### PR TITLE
Feature/add eslint rules

### PR DESCRIPTION
**Pull request by thabemmz**
Added various ESLint rulesets as we use them in Matchminds.

### CODE REVIEW

**Comment by thabemmz** [comment]
@mstalfoort make sure to also check out this one, if you'd like compare our rules with your Simpel rules and take over this feature branch to remove / add some rules.

**Comment by syphernl** [comment]
Test for Slack

**Comment by syphernl** [comment]
Test

**Comment by ankakusu** [comment]
Test

**Comment by ankakusu** [comment]
@mstalfoort Waiting for your updates! :dancer:

**Pull request closed without merging**
